### ISSUE TITLE
Error during docker build

### ISSUE THREAD

**Issue by Bloopps** [ndom91/briefkasten#23] opened 2022-10-06 21:16 UTC
### Describe the bug

After following the steps to build docker I have an error during this one =>https://docs.briefkastenhq.com/docs/self-hosting.html#docker

```
#0 19.43 > Build failed because of webpack errors
#0 19.46  ELIFECYCLE  Command failed with exit code 1.
------
failed to solve: executor failed running [/bin/sh -c pnpm build]: exit code: 1
```

There is an error in step 7=>

```
user@PC:~/docker/briefkasten$ docker-compose up -d
[+] Building 52.8s (14/21)                                                                                                                                                                                 
 => [internal] load build definition from Dockerfile                                                                                                                                                  0.1s
 => => transferring dockerfile: 2.46kB                                                                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                                                                     0.1s
 => => transferring context: 132B                                                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/node:16-bullseye-slim                                                                                                                             52.7s
 => [release  1/11] FROM docker.io/library/node:16-bullseye-slim@sha256:4fc367c89d498b455c6497cdd6211cc6a180bede77d8df80dea9acbcd5ffa19c                                                              3.5s
 => => resolve docker.io/library/node:16-bullseye-slim@sha256:4fc367c89d498b455c6497cdd6211cc6a180bede77d8df80dea9acbcd5ffa19c                                                                        0.0s
 => => sha256:154e3758048b273104a377666acd12ac09b66f2a05e695b323bc777cc4540822 4.19kB / 4.19kB                                                                                                        0.3s
 => => sha256:572071b42bdbd96b880d1f02aca7405829d929d1d956fd2d72aef4aa6bed22c4 35.35MB / 35.35MB                                                                                                      0.9s
 => => sha256:4fc367c89d498b455c6497cdd6211cc6a180bede77d8df80dea9acbcd5ffa19c 1.21kB / 1.21kB                                                                                                        0.0s
 => => sha256:7ce58a18c049245f918c4ce6a5129c89b5d9180a2bc24a8eb257d20968736a15 1.37kB / 1.37kB                                                                                                        0.0s
 => => sha256:08972e06c099ec776a8635d4ac29639b27ab676c9b2ecd490c4a269d46c3b721 7.03kB / 7.03kB                                                                                                        0.0s
 => => sha256:bd159e379b3b1bc0134341e4ffdeab5f966ec422ae04818bb69ecef08a823b05 31.42MB / 31.42MB                                                                                                      0.7s
 => => sha256:25e0c562fc17eafb2090a743dd5c12781f66ea1765c42eb2945888c8a1027170 2.77MB / 2.77MB                                                                                                        0.8s
 => => extracting sha256:bd159e379b3b1bc0134341e4ffdeab5f966ec422ae04818bb69ecef08a823b05                                                                                                             0.9s
 => => sha256:7c556d030bf688ba532e1546ea3acf5f835626d2bc3c67b3da0cdd6b49fa9e8b 450B / 450B                                                                                                            0.8s
 => => extracting sha256:154e3758048b273104a377666acd12ac09b66f2a05e695b323bc777cc4540822                                                                                                             0.0s
 => => extracting sha256:572071b42bdbd96b880d1f02aca7405829d929d1d956fd2d72aef4aa6bed22c4                                                                                                             1.2s
 => => extracting sha256:25e0c562fc17eafb2090a743dd5c12781f66ea1765c42eb2945888c8a1027170                                                                                                             0.1s
 => => extracting sha256:7c556d030bf688ba532e1546ea3acf5f835626d2bc3c67b3da0cdd6b49fa9e8b                                                                                                             0.0s
 => [internal] load build context                                                                                                                                                                     0.1s
 => => transferring context: 9.27MB                                                                                                                                                                   0.1s
 => [release  2/11] WORKDIR /app                                                                                                                                                                      0.2s
 => [release  3/11] RUN npm install -g pnpm;   pnpm --version;   pnpm setup;   mkdir -p /usr/local/share/pnpm &&  export PNPM_HOME="/usr/local/share/pnpm" &&  export PATH="$PNPM_HOME:/usr/local/sb  1.8s
 => [release  4/11] RUN addgroup --system --gid 1001 nodejs                                                                                                                                           0.6s
 => [dependencies 4/5] COPY package.json pnpm-lock.yaml prisma ./                                                                                                                                     0.1s
 => [dependencies 5/5] RUN pnpm install --frozen-lockfile                                                                                                                                            13.9s 
 => [release  5/11] RUN adduser --system --uid 1001 nextjs                                                                                                                                            0.5s 
 => [build 4/7] COPY --from=dependencies /app/node_modules ./node_modules                                                                                                                             2.4s 
 => [build 5/7] COPY . .                                                                                                                                                                              0.1s
 => [build 6/7] RUN pnpm dlx prisma generate                                                                                                                                                          7.1s
 => ERROR [build 7/7] RUN pnpm build                                                                                                                                                                 19.5s
------
 > [build 7/7] RUN pnpm build:
#0 0.778 
#0 0.778 > briefkasten@0.9.0 build /app
#0 0.778 > next build
#0 0.778 
#0 1.119 warn  - You have enabled experimental features (legacyBrowsers, browsersListForSwc) in next.config.mjs.
#0 1.120 warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
#0 1.120 
#0 1.141 Attention: Next.js now collects completely anonymous telemetry regarding usage.
#0 1.141 This information is used to shape Next.js' roadmap and prioritize features.
#0 1.141 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#0 1.141 https://nextjs.org/telemetry
#0 1.141 
#0 1.245 info  - Linting and checking validity of types...
#0 4.793 
#0 4.793 ./src/pages/index.jsx
#0 4.793 123:6  Warning: React Hook useEffect has a missing dependency: 'nextauth.user'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
#0 4.793 
#0 4.793 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
#0 4.795 info  - Creating an optimized production build...
#0 19.43 Failed to compile.
#0 19.43 
#0 19.43 Sentry CLI Plugin: Command failed: /app/node_modules/.pnpm/@sentry+cli@1.74.5/node_modules/@sentry/cli/sentry-cli releases new ydC5d0zxMx3SlD5XQJeMM
#0 19.43 error: API request failed
#0 19.43   caused by: [60] SSL peer certificate or SSH remote key was not OK (SSL certificate problem: unable to get local issuer certificate)
#0 19.43 
#0 19.43 Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
#0 19.43 Please attach the full debug log to all bug reports.
#0 19.43 
#0 19.43 Sentry CLI Plugin: Command failed: /app/node_modules/.pnpm/@sentry+cli@1.74.5/node_modules/@sentry/cli/sentry-cli releases new ydC5d0zxMx3SlD5XQJeMM
#0 19.43 error: API request failed
#0 19.43   caused by: [60] SSL peer certificate or SSH remote key was not OK (SSL certificate problem: unable to get local issuer certificate)
#0 19.43 
#0 19.43 Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
#0 19.43 Please attach the full debug log to all bug reports.
#0 19.43 
#0 19.43 
#0 19.43 > Build failed because of webpack errors
#0 19.46  ELIFECYCLE  Command failed with exit code 1.
------
failed to solve: executor failed running [/bin/sh -c pnpm build]: exit code: 1
```
Is it planned to have a docker image on a public registry (ex: docker.hub) ?
Thank you for your work 

### Reproduction

docker-compose up -d

### System Info

```Shell
System
```

### Used Package Manager

n/a

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by verchalent** [comment] 2022-10-12 14:36
Same issue on Rocky 9, Docker Compose version v2.10.2,  Docker 20.10.18.

**Comment by ayaseenx** [comment] 2022-10-17 17:17
Same issue, Debian 11, Docker 20.10.18, Compose 2.10.2,

**Comment by ndom91** [comment] 2022-11-14 18:40
Duplicate of #20.

Fixed in latest commit on `main`

**Closed by ndom91** 2022-11-14 18:40 UTC
