### ISSUE TITLE
Exception occured while editing Bookmark

### ISSUE THREAD

**Issue by paulknulst** [ndom91/briefkasten#18] opened 2022-09-22 07:42 UTC
### Describe the bug

If I try to edit a bookmark I got an "client exception"

This only happens if the menu sidebar is opened.

To avoid this error at least once:
- Close left sidebar by clicking <<
- Press edit button on Bookmark
- Edit the bookmark
- Save

Now, if i open the left sidebar without doing a full refresh it will crash with the same error.

The error:
```
framework-c87cbe29bcbbc912.js:9 TypeError: Cannot assign to read only property '0' of object '[object Array]'
    at Array.sort (<anonymous>)
    at K (132.ff888d8e4acfd3d2.js:1:17880)
    at a4 (framework-c87cbe29bcbbc912.js:9:61582)
    at uC (framework-c87cbe29bcbbc912.js:9:73264)
    at i (framework-c87cbe29bcbbc912.js:9:120633)
    at oq (framework-c87cbe29bcbbc912.js:9:107171)
    at oA (framework-c87cbe29bcbbc912.js:9:107099)
    at oW (framework-c87cbe29bcbbc912.js:9:106962)
    at o5 (framework-c87cbe29bcbbc912.js:9:103749)
    at oM (framework-c87cbe29bcbbc912.js:9:104138)
uh @ framework-c87cbe29bcbbc912.js:9
main-21fe96a802b640d5.js:1 TypeError: Cannot assign to read only property '0' of object '[object Array]'
    at Array.sort (<anonymous>)
    at K (132.ff888d8e4acfd3d2.js:1:17880)
    at a4 (framework-c87cbe29bcbbc912.js:9:61582)
    at uC (framework-c87cbe29bcbbc912.js:9:73264)
    at i (framework-c87cbe29bcbbc912.js:9:120633)
    at oq (framework-c87cbe29bcbbc912.js:9:107171)
    at oA (framework-c87cbe29bcbbc912.js:9:107099)
    at oW (framework-c87cbe29bcbbc912.js:9:106962)
    at o5 (framework-c87cbe29bcbbc912.js:9:103749)
    at oM (framework-c87cbe29bcbbc912.js:9:104138)
G @ main-21fe96a802b640d5.js:1
main-21fe96a802b640d5.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
G @ main-21fe96a802b640d5.js:1
_error-e05054ccd3c4fa56.js:1 TypeError: Cannot assign to read only property '0' of object '[object Array]'
    at Array.sort (<anonymous>)
    at K (132.ff888d8e4acfd3d2.js:1:17880)
    at a4 (framework-c87cbe29bcbbc912.js:9:61582)
    at uC (framework-c87cbe29bcbbc912.js:9:73264)
    at i (framework-c87cbe29bcbbc912.js:9:120633)
    at oq (framework-c87cbe29bcbbc912.js:9:107171)
    at oA (framework-c87cbe29bcbbc912.js:9:107099)
    at oW (framework-c87cbe29bcbbc912.js:9:106962)
    at o5 (framework-c87cbe29bcbbc912.js:9:103749)
    at oM (framework-c87cbe29bcbbc912.js:9:104138)
f.getInitialProps @ _error-e05054ccd3c4fa56.js:1
framework-c87cbe29bcbbc912.js:9 TypeError: Cannot assign to read only property '0' of object '[object Array]'
    at Array.sort (<anonymous>)
    at K (132.ff888d8e4acfd3d2.js:1:17880)
    at a4 (framework-c87cbe29bcbbc912.js:9:61582)
    at i (framework-c87cbe29bcbbc912.js:9:119736)
    at oq (framework-c87cbe29bcbbc912.js:9:107171)
    at oA (framework-c87cbe29bcbbc912.js:9:107099)
    at oW (framework-c87cbe29bcbbc912.js:9:106962)
    at o5 (framework-c87cbe29bcbbc912.js:9:103749)
    at oF (framework-c87cbe29bcbbc912.js:9:102304)
    at w (framework-c87cbe29bcbbc912.js:33:1374)
uh @ framework-c87cbe29bcbbc912.js:9
main-21fe96a802b640d5.js:1 TypeError: Cannot assign to read only property '0' of object '[object Array]'
    at Array.sort (<anonymous>)
    at K (132.ff888d8e4acfd3d2.js:1:17880)
    at a4 (framework-c87cbe29bcbbc912.js:9:61582)
    at i (framework-c87cbe29bcbbc912.js:9:119736)
    at oq (framework-c87cbe29bcbbc912.js:9:107171)
    at oA (framework-c87cbe29bcbbc912.js:9:107099)
    at oW (framework-c87cbe29bcbbc912.js:9:106962)
    at o5 (framework-c87cbe29bcbbc912.js:9:103749)
    at oF (framework-c87cbe29bcbbc912.js:9:102304)
    at w (framework-c87cbe29bcbbc912.js:33:1374)
G @ main-21fe96a802b640d5.js:1
main-21fe96a802b640d5.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

### Reproduction

Open all Bookmarks and try to edit a bookmark

### System Info

```Shell
Build locally with Docker
Build remotely on Docker Swarm
Install it without Docker


  System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 48.41 GB / 50.08 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ndom91** [comment] 2022-11-14 18:47
Thanks for reporting this, will take a look!

**Comment by ndom91** [comment] 2023-12-21 19:03
Cannot reproduce this anymore, looks like its been fixed. Closing issue.

Feel free to open a new issue if you're still running into this :+1:

**Closed by ndom91** 2023-12-21 19:03 UTC
