### ISSUE TITLE
Build error in `e97580f96455fd690f57cf16f700dcae98f1c8d3`

### ISSUE THREAD

**Issue by mzch** [ndom91/briefkasten#60] opened 2023-06-16 13:35 UTC
### Describe the bug

When running `pnpm build`, the following error occurred:
```
> briefkasten@0.9.0 build /srv/briefkasten/briefkasten
> next build

info  - Loaded env from /srv/briefkasten/briefkasten/.env
warn  - Invalid next.config.js options detected: 
  - The root value has an unexpected property, sentry, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, modularizeImports, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, skipMiddlewareUrlNormalize, skipTrailingSlashRedirect, staticPageGenerationTimeout, swcMinify, trailingSlash, transpilePackages, typescript, useFileSystemPublicRoutes, webpack).

See more info here: https://nextjs.org/docs/messages/invalid-next-config

Failed to compile.

./src/components/banner.jsx
4:42  Error: Replace `y-3·px` with `x-3·py`  prettier/prettier

./src/components/bookmark-card.jsx
55:32  Error: Replace `top-3·right` with `right-3·top`  prettier/prettier

./src/components/categoryTableRow.jsx
107:87  Error: Replace `y-1·px-2` with `x-2·py-1`  prettier/prettier

./src/components/chip.jsx
3:96  Error: Replace `y-1·px-3` with `x-3·py-1`  prettier/prettier

./src/components/dashboard-header.jsx
73:67  Error: Replace `y-1·px-2` with `x-2·py-1`  prettier/prettier

./src/components/empty-dashboard.jsx
34:101  Error: Replace `y-0·md:space-x-1` with `x-1·md:space-y-0`  prettier/prettier
37:82  Error: Replace `y-2·px-6` with `x-6·py-2`  prettier/prettier

./src/components/footer.jsx
3:90  Error: Replace `t-2·pb-6` with `b-6·pt-2`  prettier/prettier

./src/components/item-header.jsx
56:37  Error: Replace `t-0·lg:ml-4` with `l-4·lg:mt-0`  prettier/prettier
112:53  Error: Replace `mt-2·-mr-1` with `-mr-1·mt-2`  prettier/prettier

./src/components/layout.jsx
16:37  Error: Replace `top-0·left` with `left-0·top`  prettier/prettier

./src/components/modal.jsx
45:48  Error: Replace `t-5·pb-4` with `b-4·pt-5`  prettier/prettier
63:58  Error: Replace `t-0·sm:ml-4` with `l-4·sm:mt-0`  prettier/prettier
126:275  Error: Replace `t-0·sm:ml-3` with `l-3·sm:mt-0`  prettier/prettier

./src/components/pagination.jsx
39:30  Error: Replace `left-1/2·bottom-4` with `bottom-4·left-1/2`  prettier/prettier

./src/components/quick-add.jsx
150:37  Error: Replace `right-8·bottom-24` with `bottom-24·right-8`  prettier/prettier
364:86  Error: Replace `y-2·px-4` with `x-4·py-2`  prettier/prettier
450:133  Error: Replace `y-2·px-4` with `x-4·py-2`  prettier/prettier
501:49  Error: Replace `top-0·left` with `left-0·top`  prettier/prettier

./src/components/sidebar.jsx
417:32  Error: Replace `l-2·mb-4` with `b-4·ml-2`  prettier/prettier
513:47  Error: Replace `left-0·bottom-16` with `bottom-16·left-0`  prettier/prettier

./src/components/slide-out.jsx
138:46  Error: Replace `top-0·left-0·-ml-8·flex·pt-4·pr-2` with `left-0·top-0·-ml-8·flex·pr-2·pt-4`  prettier/prettier
194:47  Error: Replace `top-2·right` with `right-2·top`  prettier/prettier
417:88  Error: Replace `y-2·px-4` with `x-4·py-2`  prettier/prettier
503:136  Error: Replace `y-2·px-4` with `x-4·py-2`  prettier/prettier
541:90  Error: Replace `transparent·border-slate-600·py-2·px-4` with `slate-600·border-transparent·px-4·py-2`  prettier/prettier

./src/components/tagTableRow.jsx
107:87  Error: Replace `y-1·px-2` with `x-2·py-1`  prettier/prettier

./src/components/toastContainer.jsx
8:47  Error: Replace `top-4·right-4·z-50·flex·w-2/3·max-w-md·flex-col·items-end·sm:top-10·sm:right` with `right-4·top-4·z-50·flex·w-2/3·max-w-md·flex-col·items-end·sm:right-10·sm:top`  prettier/prettier

./src/components/toastElements.jsx
37:27  Error: Replace `top-2·right` with `right-2·top`  prettier/prettier
91:27  Error: Replace `top-2·right` with `right-2·top`  prettier/prettier
145:27  Error: Replace `top-2·right` with `right-2·top`  prettier/prettier

./src/pages/auth/signin.jsx
108:34  Error: Replace `top-0·left-0·z-10·flex·h-[250%]·w-[110%]·translate-x-[-55%]·translate-y-[-28%]·rotate-[22deg]·items-center·bg-slate-900·md:w-[70%]·md:translate-y-[-20%]·md:translate-x-[-3` with `left-0·top-0·z-10·flex·h-[250%]·w-[110%]·translate-x-[-55%]·translate-y-[-28%]·rotate-[22deg]·items-center·bg-slate-900·md:w-[70%]·md:translate-x-[-30%]·md:translate-y-[-2`  prettier/prettier
198:122  Error: Replace `y-2·px-4` with `x-4·py-2`  prettier/prettier
210:28  Error: Replace `top-0·right` with `right-0·top`  prettier/prettier

./src/pages/categories.jsx
104:72  Error: Replace `y-1·px-2` with `x-2·py-1`  prettier/prettier
161:95  Error: Replace `y-1·px-2` with `x-2·py-1`  prettier/prettier
167:100  Error: Replace `y-1·px-2` with `x-2·py-1`  prettier/prettier

./src/pages/index.jsx
123:6  Warning: React Hook useEffect has a missing dependency: 'nextauth.user'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./src/pages/settings.jsx
209:57  Error: Replace `y-1·px-2` with `x-2·py-1`  prettier/prettier

./src/pages/tags.jsx
105:72  Error: Replace `y-1·px-2` with `x-2·py-1`  prettier/prettier
160:95  Error: Replace `y-1·px-2` with `x-2·py-1`  prettier/prettier
166:100  Error: Replace `y-1·px-2` with `x-2·py-1`  prettier/prettier

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
info  - Linting and checking validity of types . ELIFECYCLE  Command failed with exit code 1.
```

Commit: `e97580f96455fd690f57cf16f700dcae98f1c8d3`

### Reproduction

Clone the repository > `pnpm install` > `pnpm build`

### System Info

```Shell
OS: Debian `12.0`
Node.js: `v16.20.0`
pnpm: `7.5.1`
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ndom91** [comment] 2023-12-21 18:45
These seem to be some messed up prettier suggestions, following these suggestions would break a lot of the classes. Unfortunately I can't reproduce it either. Running `pnpm build` on current `main` (`e97580f`) runs fine. Closing for now

**Closed by ndom91** 2023-12-21 18:45 UTC
